name: Test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  typos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: typos
        uses: crate-ci/typos@v1.12.12

  voicevox-shared-workflow:
    uses: VOICEVOX/.github/.github/workflows/shared.yml@main

    # Super Linter に必要
    permissions:
      contents: read
      packages: read
      statuses: write
