name: Test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  typos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: typos
        uses: crate-ci/typos@v1.12.12

  voicevox_shared_workflow:
    uses: VOICEVOX/.github/.github/workflows/shared.yml@main

    # Super Linter に必要
    permissions:
      contents: read
      packages: read
      statuses: write

    with:
      # Python系の不要なものは無効化
      # リソースファイルとして存在してるファイルのPrettierも無効化
      # FIXME: BASH_EXEC・CHECKOV・SHELL_SHFMTはできれば有効にしたい
      super_linter_env_vars: |
        VALIDATE_PYTHON_FLAKE8=false
        VALIDATE_PYTHON_RUFF=false
        VALIDATE_PYTHON_PYINK=false
        VALIDATE_PYTHON_PYLINT=false
        VALIDATE_JSON_PRETTIER=false
        VALIDATE_MARKDOWN_PRETTIER=false
        VALIDATE_YAML_PRETTIER=false
        VALIDATE_BASH_EXEC=false
        VALIDATE_CHECKOV=false
        VALIDATE_SHELL_SHFMT=false

  test_terms:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Run terms validation script
        run: |
          python scripts/validate_terms.py
