name: Test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  typos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: typos
        uses: crate-ci/typos@47912c390ab44028f45fe2abc0bb5c6d97392bf8 # v1.12.12

  pinact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: pinact
        uses: suzuki-shunsuke/pinact-action@28aeb220eb3252ad0d4422dd5d9368e925acbd8d # v1.3.0
        with:
          skip_push: "true"
          min_age: "7"

  voicevox_shared_workflow:
    uses: VOICEVOX/.github/.github/workflows/shared.yml@main

    # Super Linter に必要
    permissions:
      contents: read
      packages: read
      statuses: write

    with:
      # Python系の不要なものは無効化
      # リソースファイルとして存在してるファイルのPrettierも無効化
      # FIXME: BASH_EXEC・CHECKOV・SHELL_SHFMTはできれば有効にしたい
      super_linter_env_vars: |
        VALIDATE_PYTHON_FLAKE8=false
        VALIDATE_PYTHON_RUFF=false
        VALIDATE_PYTHON_PYINK=false
        VALIDATE_PYTHON_PYLINT=false
        VALIDATE_JSON_PRETTIER=false
        VALIDATE_MARKDOWN_PRETTIER=false
        VALIDATE_YAML_PRETTIER=false
        VALIDATE_BASH_EXEC=false
        VALIDATE_CHECKOV=false
        VALIDATE_SHELL_SHFMT=false

  test_terms:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: "3.x"

      - name: Run terms validation script
        run: |
          python scripts/validate_terms.py
