name: Test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  typos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: typos
        uses: crate-ci/typos@v1.12.12

  voicevox_shared_workflow:
    uses: VOICEVOX/.github/.github/workflows/shared.yml@main

    # Super Linter に必要
    permissions:
      contents: read
      packages: read
      statuses: write

  test_terms:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Run terms validation script
        run: |
          python scripts/validate_terms.py
